export const AUTH_CONST = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_RESET: "REGISTER_RESET",

  TOKEN_SUCCESS: "TOKEN_SUCCESS",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
  LOGIN_REQUEST_RESET: "LOGIN_REQUEST_RESET",

  GET_HOME_CONTENT_REQUEST: "GET_HOME_CONTENT_REQUEST",
  GET_HOME_CONTENT_SUCCESS: "GET_HOME_CONTENT_SUCCESS",
  GET_HOME_CONTENT_FAILURE: "GET_HOME_CONTENT_FAILURE",

  CHANGE_PASSWORD_RESET: "CHANGE_PASSWORD_RESET",

  STATUS_UPDATE: "STATUS_UPDATE",
};

export const ACCOUNT_CONST = {
  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  CONFIRM_F_PASSWORD_REQUEST: "CONFIRM_F_PASSWORD_REQUEST",
  CONFIRM_F_PASSWORD_SUCCESS: "CONFIRM_F_PASSWORD_SUCCESS",
  CONFIRM_F_PASSWORD_FAILURE: "CONFIRM_F_PASSWORD_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  MY_PROFILE_REQUEST: "MY_PROFILE_REQUEST",
  MY_PROFILE_SUCCESS: "MY_PROFILE_SUCCESS",
  MY_PROFILE_FAILURE: "MY_PROFILE_FAILURE",
};
export const CLAIM = {
  CREATE_CLAIM_REQUEST: "CREATE_CLAIM_REQUEST",
  CREATE_CLAIM_SUCCESS: "CREATE_CLAIM_SUCCESS",
  CREATE_CLAIM_FAILURE: "CREATE_CLAIM_FAILURE",

  GET_CLAIMS_REQUEST: "GET_CLAIMS_REQUEST",
  GET_CLAIMS_SUCCESS: "GET_CLAIMS_SUCCESS",
  GET_CLAIMS_FAILURE: "GET_CLAIMS_FAILURE",

  GET_CLAIMS_BY_CODE_REQUEST: "GET_CLAIMS_BY_CODE_REQUEST",
  GET_CLAIMS_BY_CODE_SUCCESS: "GET_CLAIMS_BY_CODE_SUCCESS",
  GET_CLAIMS_BY_CODE_FAILURE: "GET_CLAIMS_BY_CODE_FAILURE",

  APPROVE_CLAIM_REQUEST: "APPROVE_CLAIM_REQUEST",
  APPROVE_CLAIM_SUCCESS: "APPROVE_CLAIM_SUCCESS",
  APPROVE_CLAIM_FAILURE: "APPROVE_CLAIM_FAILURE",

  GET_CLAIM_CHANNEL_REQUEST: "GET_CLAIM_CHANNEL_REQUEST",
  GET_CLAIM_CHANNEL_SUCCESS: "GET_CLAIM_CHANNEL_SUCCESS",
  GET_CLAIM_CHANNEL_FAILURE: "GET_CLAIM_CHANNEL_FAILURE",

  UPDATE_CLAIM_BY_AGENT_REQUEST: "UPDATE_CLAIM_BY_AGENT_REQUEST",
  UPDATE_CLAIM_BY_AGENT_SUCCESS: "UPDATE_CLAIM_BY_AGENT_SUCCESS",
  UPDATE_CLAIM_BY_AGENT_FAILURE: "UPDATE_CLAIM_BY_AGENT_FAILURE",

  UPDATE_TICKET_ATTACHMENT_REQUEST: "UPDATE_TICKET_ATTACHMENT_REQUEST",
  UPDATE_TICKET_ATTACHMENT_SUCCESS: "UPDATE_TICKET_ATTACHMENT_SUCCESS",
  UPDATE_TICKET_ATTACHMENT_FAILURE: "UPDATE_TICKET_ATTACHMENT_FAILURE",

  UPDATE_CLAIM_ATTACHMENT_REQUEST: "UPDATE_CLAIM_ATTACHMENT_REQUEST",
  UPDATE_CLAIM_ATTACHMENT_SUCCESS: "UPDATE_CLAIM_ATTACHMENT_SUCCESS",
  UPDATE_CLAIM_ATTACHMENT_FAILURE: "UPDATE_CLAIM_ATTACHMENT_FAILURE",

  GET_TICKET_ATTACHMENT_REQUEST: "GET_TICKET_ATTACHMENT_REQUEST",
  GET_TICKET_ATTACHMENT_SUCCESS: "GET_TICKET_ATTACHMENT_SUCCESS",
  GET_TICKET_ATTACHMENT_FAILURE: "GET_TICKET_ATTACHMENT_FAILURE",

  GET_CLAIM_ATTACHMENT_REQUEST: "GET_CLAIM_ATTACHMENT_REQUEST",
  GET_CLAIM_ATTACHMENT_SUCCESS: "GET_CLAIM_ATTACHMENT_SUCCESS",
  GET_CLAIM_ATTACHMENT_FAILURE: "GET_CLAIM_ATTACHMENT_FAILURE",
};

export const CATEGORY_CONST = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
};

export const SUB_CATEGORY_CONST = {
  GET_SUB_CATEGORY_REQUEST: "GET_SUB_CATEGORY_REQUEST",
  GET_SUB_CATEGORY_SUCCESS: "GET_SUB_CATEGORY_SUCCESS",
  GET_SUB_CATEGORY_FAILURE: "GET_SUB_CATEGORY_FAILURE",

  GET_SUB_CATEGORY_BY_C_ID_REQUEST: "GET_SUB_CATEGORY_BY_C_ID_REQUEST",
  GET_SUB_CATEGORY_BY_C_ID_SUCCESS: "GET_SUB_CATEGORY_BY_C_ID_SUCCESS",
  GET_SUB_CATEGORY_BY_C_ID_FAILURE: "GET_SUB_CATEGORY_BY_C_ID_FAILURE",
};

export const SUB_SUB_CATEGORY_CONST = {
  GET_SUB_SUB_CATEGORY_REQUEST: "GET_SUB_SUB_CATEGORY_REQUEST",
  GET_SUB_SUB_CATEGORY_SUCCESS: "GET_SUB_SUB_CATEGORY_SUCCESS",
  GET_SUB_SUB_CATEGORY_FAILURE: "GET_SUB_SUB_CATEGORY_FAILURE",
};

export const STATION_CONST = {
  GET_STATION_REQUEST: "GET_STATION_REQUEST",
  GET_STATION_SUCCESS: "GET_STATION_SUCCESS",
  GET_STATION_FAILURE: "GET_STATION_FAILURE",
};
export const CREATE_CUSTOMER_CONST = {
  POST_CREATE_CUSTOMER_REQUEST: "POST_CREATE_CUSTOMER_REQUEST",
  POST_CREATE_CUSTOMER_SUCCESS: "POST_CREATE_CUSTOMER_SUCCESS",
  POST_CREATE_CUSTOMER_FAILURE: "POST_CREATE_CUSTOMER_FAILURE",
};

export const SEARCH_CUSTOMER_DATA = {
  GET_CUSTOMER_REQUEST: "GET_CUSTOMER_REQUEST",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE: "GET_CUSTOMER_FAILURE",
};

export const TARIF_CONST = {
  GET_TARIFS_REQUEST: "GET_TARIFS_REQUEST",
  GET_TARIFS_SUCCESS: "GET_TARIFS_SUCCESS",
  GET_TARIFS_FAILURE: "GET_TARIFS_FAILURE",
};

export const TRAIN_TYPE_CONST = {
  GET_TRAIN_TYPES_REQUEST: "GET_TRAIN_TYPES_REQUEST",
  GET_TRAIN_TYPES_SUCCESS: "GET_TRAIN_TYPES_SUCCESS",
  GET_TRAIN_TYPES_FAILURE: "GET_TRAIN_TYPES_FAILURE",
};
